export const INIT_MODULE       = 'INIT_MODULE'
export const UPDATE_MODULE     = 'UPDATE_MODULE'
export const SET_ACTIVE_MODULE = 'SET_ACTIVE_MODULE'

export const FETCH_RULE = 'FETCH_RULE'
export const FETCH_LUCKY_LIST = 'FETCH_LUCKY_LIST'